// Post-build prerender. Runs after both the client build (dist/) and the SSR
// build (dist-ssr/). For every public route it injects route-specific <head>
// metadata and server-rendered body content into a copy of the built
// dist/index.html, writing both `<route>.html` and `<route>/index.html` so the
// route resolves whether the static host uses ".html" or directory-index
// resolution. Also (re)generates sitemap.xml and robots.txt.
//
// The route metadata, body rendering, and case-study JSON-LD all come from the
// shared SSR bundle (src/entry-server.tsx) so the prerendered output can never
// drift from the runtime.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const dist = path.join(root, "dist");

const { renderRoute, publicRoutes, SITE_ORIGIN } = await import(
  path.join(root, "dist-ssr", "entry-server.js")
);

const META_RE = /<!-- ROUTE_META_START[\s\S]*?ROUTE_META_END -->/;
const ROOT_DIV = '<div id="root"></div>';

const template = fs.readFileSync(path.join(dist, "index.html"), "utf8");
if (!META_RE.test(template)) {
  throw new Error("ROUTE_META markers not found in dist/index.html");
}
if (!template.includes(ROOT_DIV)) {
  throw new Error('<div id="root"></div> not found in dist/index.html');
}

function buildHtml(routePath) {
  const { appHtml, headTags } = renderRoute(routePath);
  return template
    .replace(
      META_RE,
      `<!-- ROUTE_META_START : generated by scripts/prerender.mjs for ${routePath} -->\n    ${headTags}\n    <!-- ROUTE_META_END -->`,
    )
    .replace(ROOT_DIV, `<div id="root">${appHtml}</div>`);
}

function writeRoute(routePath) {
  const html = buildHtml(routePath);
  if (routePath === "/") {
    fs.writeFileSync(path.join(dist, "index.html"), html);
    return;
  }
  const rel = routePath.replace(/^\//, ""); // "about" | "work/frog"
  if (rel.includes("/")) {
    fs.mkdirSync(path.join(dist, path.dirname(rel)), { recursive: true });
  }
  fs.writeFileSync(path.join(dist, `${rel}.html`), html);
  const dir = path.join(dist, rel);
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, "index.html"), html);
}

const routes = publicRoutes();
for (const route of routes) writeRoute(route);

// ── sitemap.xml + robots.txt ─────────────────────────────────────────────────
const lastmod = new Date().toISOString().slice(0, 10);
const sitemap =
  `<?xml version="1.0" encoding="UTF-8"?>\n` +
  `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
  routes
    .map(
      (route) =>
        `  <url>\n    <loc>${SITE_ORIGIN}${route}</loc>\n    <lastmod>${lastmod}</lastmod>\n  </url>`,
    )
    .join("\n") +
  `\n</urlset>\n`;
fs.writeFileSync(path.join(dist, "sitemap.xml"), sitemap);

fs.writeFileSync(
  path.join(dist, "robots.txt"),
  `User-agent: *\nAllow: /\n\nSitemap: ${SITE_ORIGIN}/sitemap.xml\n`,
);

console.log(
  `[prerender] wrote ${routes.length} routes (body + metadata) + sitemap.xml + robots.txt`,
);
